const Portfoliodata = [
    {
        id: 1,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com',
        markdown: `![Logo](https://raw.githubusercontent.com/rjsgud49/rjsgud49/main/assets/logo.png)

## 👀 자기소개 👀

현재 **경북소프트웨어고등학교 2학년** 재학 중  
목표는 **React + Nest 기반의 풀스택 개발자**

---/*  */

## ✨ 개발스택 ✨

![CSS](https://ziadoua.github.io/m3-Markdown-Badges/badges/CSS/css2.svg)
![HTML](https://ziadoua.github.io/m3-Markdown-Badges/badges/HTML/html2.svg)
![JS](https://ziadoua.github.io/m3-Markdown-Badges/badges/Javascript/javascript3.svg)
![TS](https://ziadoua.github.io/m3-Markdown-Badges/badges/TypeScript/typescript1.svg)
![Redux](https://ziadoua.github.io/m3-Markdown-Badges/badges/Redux/redux1.svg)
![React](https://ziadoua.github.io/m3-Markdown-Badges/badges/React/react2.svg)
![Axios](https://ziadoua.github.io/m3-Markdown-Badges/badges/Axios/axios1.svg)
![Vite](https://ziadoua.github.io/m3-Markdown-Badges/badges/ViteJS/vitejs2.svg)

---

## 🔧 Tools 🔧

![Figma](https://ziadoua.github.io/m3-Markdown-Badges/badges/Figma/figma2.svg)
![GitHub](https://ziadoua.github.io/m3-Markdown-Badges/badges/Github/github2.svg)
![Windows11](https://ziadoua.github.io/m3-Markdown-Badges/badges/Windows11/windows111.svg)
![VSCode](https://ziadoua.github.io/m3-Markdown-Badges/badges/VisualStudioCode/visualstudiocode1.svg)
![Git](https://ziadoua.github.io/m3-Markdown-Badges/badges/Git/git1.svg)
![IntelliJ](https://ziadoua.github.io/m3-Markdown-Badges/badges/IDEA/idea1.svg)
![Illustrator](https://ziadoua.github.io/m3-Markdown-Badges/badges/Illustrator/illustrator1.svg)
![Notion](https://ziadoua.github.io/m3-Markdown-Badges/badges/Notion/notion1.svg)
![Ubuntu](https://ziadoua.github.io/m3-Markdown-Badges/badges/Ubuntu/ubuntu1.svg)

---

## 🌱 공부 중...

![NestJS](https://ziadoua.github.io/m3-Markdown-Badges/badges/NestJS/nestjs1.svg)
![Express](https://ziadoua.github.io/m3-Markdown-Badges/badges/Express/express2.svg)

---

## ⭐ 사용 언어 통계

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rjsgud49)](https://github.com/anuraghazra/github-readme-stats)

---

## 🐶 동물농장 🐶

![GitAnimals](https://render.gitanimals.org/farms/rjsgud49)

---

## 📶 Contact 📶

[![Gmail](https://img.shields.io/badge/qkrrjsgud49@gmail.com-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:qkrrjsgud49@gmail.com)  
[![Velog](https://img.shields.io/badge/Velog-1EBC8F?style=for-the-badge&logo=velog&logoColor=white)](https://velog.io/@rjsgud49)  
[![Discord](https://ziadoua.github.io/m3-Markdown-Badges/badges/Discord/discord1.svg)](https://discord.gg/vZUxZJHKQp)  
[![Instagram](https://ziadoua.github.io/m3-Markdown-Badges/badges/Instagram/instagram1.svg)](https://www.instagram.com/qkrrjsgud49/)
`
    },
    {
        id: 2,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 3,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 4,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 5,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 6,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 7,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 8,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 9,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 10,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 11,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 12,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 13,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 14,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 15,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 16,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 17,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 18,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 19,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 20,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    }
];
export { Portfoliodata };