const Portfoliodata = [
    {
        id: 1,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 2,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 3,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 4,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 5,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 6,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 7,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 8,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 9,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 10,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 11,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 12,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 13,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 14,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 15,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 16,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 17,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 18,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 19,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    },
    {
        id: 20,
        name: '박건형',
        grade: '2학년',
        classname: '소프트웨어개발과',
        tags: ['#웹디자인', '#Frontend', '#React'],
        github: 'github.com',
        email: 'Email@.com'
    }
];
export { Portfoliodata };